---
- name: Creating new LVM
  hosts: all
  become: yes
  tasks:
    - name: Create Physical Volume
      community.general.lvg:
        vg: vg1
        pvs: /dev/sdb

    - name: Create Volume Group
      community.general.lvg:
        vg: vg1
        pvs: /dev/sdb

    - name: Create Logical Volume
      community.general.lvol:
        vg: vg1
        lv: lv1
        size: 5g

    - name: Create File System
      ansible.builtin.filesystem:
        fstype: xfs
        dev: /dev/vg1/lv1

    - name: Create mount directory
      ansible.builtin.file:
        path: /root/newdir
        state: directory

    - name: Mount Logical Volume
      ansible.builtin.mount:
        path: /root/newdir
        src: /dev/vg1/lv1
        fstype: xfs
        state: mounted

    - name: Ensure mount is persistent
      ansible.builtin.mount:
        path: /root/newdir
        src: /dev/vg1/lv1
        fstype: xfs
        state: present
